### ISSUE TITLE
Sweep: refactor the code of server.py, client.py in TCP Chat App Folder 

### ISSUE THREAD

**Issue by thenithinbalaji** [thenithinbalaji/Networks-Lab#1]
<details>
<summary>Checklist</summary>

- [X] `TCP Chat App/server.py`
> * Encapsulate the code in a class named "Server" with methods for each operation (binding, listening, accepting connections, receiving data, sending data, and closing the connection).
> • Add error handling for socket operations to prevent the program from crashing due to unexpected errors.
> • Add comments to explain what each part of the code does.

- [X] `TCP Chat App/client.py`
> * Encapsulate the code in a class named "Client" with methods for each operation (connecting, sending data, receiving data, and closing the connection).
> • Add error handling for socket operations to prevent the program from crashing due to unexpected errors.
> • Add comments to explain what each part of the code does.

</details>

**Comment by kevinlu1248** [comment]
Hey @thenithinbalaji, I'm a developer of Sweep. You have to be more specific in how to refactor the files otherwise Sweep will either hallucinate or fail.

**Comment by kevinlu1248** [comment]
Oh never mind it looks like the bug has to do with the spaces in your folder names

**Comment by kevinlu1248** [comment]
Hey just fixed this issue, gonna re-run for you

**Comment by thenithinbalaji** [comment]
@kevinlu1248 I was just trying out Sweep. Such a cool product 🤟

**Comment by kevinlu1248** [comment]
Thanks! Glad you're liking it @thenithinbalaji
